services:
  order-service:
    container_name: order-service
    image: order-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/order?useUnicode=true&characterEncoding=utf-8
      - SPRING_DATASOURCE_USERNAME=order
      - SPRING_DATASOURCE_PASSWORD=${NEW_USER_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - GOOGLE_MAP_API_KEY=${GOOGLE_MAP_API_KEY}

  mysql-db:
    container_name: mysql-db
    image: mysql:8.4.0
    restart: always
    ports:
      - "33066:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=order
      - TZ=Asia/Hong_Kong
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
   image: redis:7.0.15-alpine3.20
   ports:
     - "6379:6379"
   container_name: redis
   restart: unless-stopped
   volumes:
     - ./redis_data:/data