spring:
  application:
    name: order-service
  jpa:
    database: MYSQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33066/order
    username:
    password:
  data:
    redis:
      host: localhost
      port: 6379
  mvc:
    converters:
      preferred-json-mapper: jackson

server:
  port: 8080

google-map:
  api-key:


project:
  version: "@project.version@"


timestamp: "@timestamp@"

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
